services:
  clientes-api:
    image: clientes-api:latest
    container_name: clientes-api
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"

    expose:
      - "8000"

    environment:
      DB_HOST: clientes-api-db
      DB_NAME: clientes_db
      DB_USER: clientes
      DB_PASSWORD: clientes123
      DB_PORT: "3306"

      VIRTUAL_HOST: clientes-api.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"

    depends_on:
      - clientes-api-db

    networks:
      - backend
      - nginx-proxy

    restart: unless-stopped


  clientes-api-db:
    image: mariadb:10.6
    container_name: clientes-api-db

    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes
      MYSQL_PASSWORD: clientes123
      MYSQL_ROOT_PASSWORD: root123

    volumes:
      - clientes_api_db_data:/var/lib/mysql

    networks:
      - backend

    restart: unless-stopped


networks:
  backend:
    name: clientes_api_backend

  nginx-proxy:
    external: true


volumes:
  clientes_api_db_data:
    name: clientes_api_db_data
