services:
  db:
    image: mariadb:10.6
    container_name: clientes-api-db
    environment:
      - MARIADB_DATABASE=clientes_db
      - MARIADB_USER=profesor
      - MARIADB_PASSWORD=4688
      - MARIADB_ROOT_PASSWORD=root4688
    volumes:
      - clientes_db_data:/var/lib/mysql
      - ./docs/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    networks:
      - backend
    restart: unless-stopped

  app:
    build: .
    image: clientes-api:latest
    container_name: clientes-api
    environment:
      - DB_HOST=db
      - DB_USER=profesor
      - DB_PASSWORD=4688
      - DB_NAME=clientes_db
      - DB_PORT=3306
      - VIRTUAL_HOST=clientes-api.docker.sulbaranjc.com
      - VIRTUAL_PORT=8000
    depends_on:
      - db
    networks:
      - backend
      - proxy
    restart: unless-stopped

volumes:
  clientes_db_data:

networks:
  backend:
  proxy:
    external: true
    name: proxy
