services:
  clientes-api:
    image: clientes-api:latest
    restart: always

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    expose:
      - "8000"

    environment:
      - VIRTUAL_HOST=clientes-api.docker.sulbaranjc.com
      - VIRTUAL_PORT=8000

    depends_on:
      - clientes-api-db

    networks:
      - clientes_api_backend
      - nginx-proxy


  clientes-api-db:
    image: mariadb:10.6
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes_user
      MYSQL_PASSWORD: clientes_pass

    volumes:
      - clientes_api_clientes_db_data:/var/lib/mysql

    networks:
      - clientes_api_backend


volumes:
  clientes_api_clientes_db_data:


networks:
  clientes_api_backend:
    external: true

  nginx-proxy:
    external: true
