services:
  clientes-api:
    image: clientes-api:latest
    container_name: clientes-api
    restart: unless-stopped

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    environment:
      # nginx-proxy
      VIRTUAL_HOST: clientes-api.docker.sulbaranjc.com
      VIRTUAL_PORT: 8000

      # DB
      DB_HOST: clientes-api-db
      DB_PORT: 3306
      DB_NAME: clientes_db
      DB_USER: clientes_user
      DB_PASSWORD: clientes_pass

    depends_on:
      - clientes-api-db

    networks:
      - nginx-proxy
      - clientes_api_backend

  clientes-api-db:
    image: mariadb:10.6
    container_name: clientes-api-db
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_USER: clientes_user
      MYSQL_PASSWORD: clientes_pass
      MYSQL_ROOT_PASSWORD: rootpass

    volumes:
      - clientes_api_db_data:/var/lib/mysql

    networks:
      - clientes_api_backend

volumes:
  clientes_api_db_data:

networks:
  nginx-proxy:
    external: true

  clientes_api_backend:
    external: true
