name: Deploy clientes_api

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy clientes_api via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            echo "ğŸ“‚ Entrando en carpeta de despliegue"
            cd /home/sulbaranjc/apps/clientes_api

            echo "ğŸ“¥ Actualizando cÃ³digo desde GitHub"
            if [ ! -d .git ]; then
              git clone https://github.com/sulbaranjc/clientes_api.git .
            else
              git pull origin deploy
            fi

            echo "ğŸ³ Construyendo y levantando contenedor (sin down)"
            docker compose up -d --build

            echo "âœ… Despliegue finalizado sin afectar otros servicios"
